MAX_CHANNELS_PER_BANK = 16

INPUT_CHANNEL_COUNT = 17
AUX_CHANNEL_COUNT = 8
DCA_CHANNEL_COUNT = 8
MAIN_CHANNEL_COUNT = 1

_IA_CHANNEL_COUNT = INPUT_CHANNEL_COUNT + AUX_CHANNEL_COUNT
_IAD_CHANNEL_COUNT = _IA_CHANNEL_COUNT + DCA_CHANNEL_COUNT
_TOTAL_CHANNEL_COUNT = _IAD_CHANNEL_COUNT + MAIN_CHANNEL_COUNT

INPUT_CHANNEL_RANGE = range(INPUT_CHANNEL_COUNT)
AUX_CHANNEL_RANGE = range(INPUT_CHANNEL_COUNT, _IA_CHANNEL_COUNT)
DCA_CHANNEL_RANGE = range(_IA_CHANNEL_COUNT, _IAD_CHANNEL_COUNT)
MAIN_CHANNEL_RANGE = range(_IAD_CHANNEL_COUNT, _TOTAL_CHANNEL_COUNT)

INPUT_PARAM_COUNT = 52
