# Set constants

INPUT_CHANNEL_COUNT = 48
AUX_CHANNEL_COUNT = 8
DCA_CHANNEL_COUNT = 7
DCA2_CHANNEL_COUNT = 8

INPUT_PARAM_COUNT = 52
MAX_PARAM_COUNT_PER_REMOTE = 1024

# Derived constants

_IA_CHANNEL_COUNT = INPUT_CHANNEL_COUNT + AUX_CHANNEL_COUNT
_IAD_CHANNEL_COUNT = _IA_CHANNEL_COUNT + DCA_CHANNEL_COUNT
TOTAL_CHANNEL_COUNT = _IAD_CHANNEL_COUNT + DCA2_CHANNEL_COUNT

INPUT_CHANNEL_RANGE = range(INPUT_CHANNEL_COUNT)
AUX_CHANNEL_RANGE = range(INPUT_CHANNEL_COUNT, _IA_CHANNEL_COUNT)
DCA_CHANNEL_RANGE = range(_IA_CHANNEL_COUNT, _IAD_CHANNEL_COUNT)
DCA2_CHANNEL_RANGE = range(_IAD_CHANNEL_COUNT, TOTAL_CHANNEL_COUNT)
MAIN_CHANNEL_RANGE = range(TOTAL_CHANNEL_COUNT, TOTAL_CHANNEL_COUNT + 1)

MAX_INPUT_CHANNEL_COUNT_PER_REMOTE = MAX_PARAM_COUNT_PER_REMOTE // INPUT_PARAM_COUNT
